### PR TITLE
Add information about adding Scoped Registries to the Package Manager

### PR DESCRIPTION
**Pull request by singlerider**
We don't currently have information about Scoped Registry addition/alteration. Now, we can:

Screen Shot 2023-04-06 at 8 31 31 AM

### CODE REVIEW

**Comment by katvlasova** [comment]
Looks good to me

**Review by katvlasova — APPROVED** [review]
LGTM

**Comment by singlerider** [comment]
Oops. We'll have to fix it later.

**Comment by singlerider** [comment]
This will fix it: [113eff722085615efa8d5af8b47af8c90657d90a https://github.com/magicleap/developer-portal-docs/pull/70/commits/113eff722085615efa8d5af8b47af8c90657d90a](https://github.com/magicleap/developer-portal-docs/pull/70/commits/113eff722085615efa8d5af8b47af8c90657d90a)

**Pull request merged**
